version: "3.3"

services:
  blog:
    image: ghost:latest
    ports:
      - "80:2368"
    networks:
      - todo_net
    volumes:
      - type: volume
        source: dbdata
        target: /data/ghost/content
    environment: 
      - name=SpringreBoot
      - url=https://springreboot.com/
networks:
  todo_net:

volumes:
  dbdata:
